# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Install the Intel libsgx package dependencies
  yum:
    name: "{{ intel_sgx_package_dependencies }}"
    state: latest
  retries: 10
  register: install_sgx_dependencies
  until: install_sgx_dependencies is success

- name: Create Intel SGX directory
  file:
    path: "{{ intel_sgx_directory }}"
    state: directory

- name: Download Intel SGX local rpm repo tgz
  get_url:
    url: "{{ intel_sgx_rpm_repo_tgz_url }}"
    dest: "/tmp/sgx_rpm_local_repo.tgz"
    timeout: 120
  retries: 5

- name: Unarchive Intel SGX local rpm repo tgz
  unarchive:
    src: "/tmp/sgx_rpm_local_repo.tgz"
    dest: "{{ intel_sgx_directory }}"
    remote_src: yes

- name: Enable local Intel SGX repo
  yum_repository:
    name: intel-sgx-local-repo
    description: Intel SGX local RPM repository
    baseurl: "file://{{ intel_sgx_directory }}/sgx_rpm_local_repo"
    enabled: yes
    gpgcheck: no

- name: Install Intel SGX packages
  yum:
    name: "{{ intel_sgx_packages }}"
    state: latest
  retries: 10
  register: install_sgx
  until: install_sgx is success

- name: Install the Intel DCAP packages
  yum:
    name: "{{ intel_dcap_packages }}"
    state: latest
  when: flc_enabled|bool
  retries: 10
  register: install_dcap
  until: install_dcap is success

- name: Cleanup installation
  file:
    path: "/tmp/sgx_rpm_local_repo.tgz"
    state: absent
