# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- import_role:
    name: linux/common
    tasks_from: apt-repo-microsoft.yml

- name: Install the official Azure-DCAP-Client APT package
  apt:
    name: az-dcap-client
    state: present
    update_cache: yes
