# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Install apt-transport-https APT package
  apt:
    name: apt-transport-https
    state: present

- name: Add Microsoft APT repository key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add Microsoft APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
