# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- hosts: windows-agents
  any_errors_fatal: true
  become_method: runas
  tasks:
    - name: OE setup | Run the install-windows-prereqs.ps1 script (this may take a while)
      script: ../install-windows-prereqs.ps1 -IntelPSWURL "https://oejenkins.blob.core.windows.net/oejenkins/Intel_SGX_PSW_for_Windows_v2.3.100.49777.exe" -IntelDCAPURL "https://oejenkins.blob.core.windows.net/oejenkins/Intel_SGX_DCAP_for_Windows_v1.1.100.49925.exe"

    - name: OE setup | Reboot the node
      win_reboot:

    - import_role:
        name: windows/openenclave
        tasks_from: validation.yml

    - import_role:
        name: windows/az-dcap-client
        tasks_from: validation.yml
